version: "3.7"
services:

  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - ./mysql/mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db_data:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
    env_file:
      - ./pma/pma.env

networks:
  default:
    name: app
