version: "3.7"

services:
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=[PASSWORD]
    ports:
      - "3306:[PORT_SQL]"
    volumes:
      - ./mysql:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=https://[DOMAIN_PMA]/

networks:
  default:
    name: app
