version: "3.7"

services:
  registry:
    image: registry
    container_name: registry
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./registry:/var/lib/registry

networks:
  default:
    name: app
