version: "3.7"
services:

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/error:/etc/nginx/error
      - ./nginx/logs:/var/log/nginx

networks:
  default:
    name: app
