version: "3.7"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf    # Базовая конфигураци
      - ./nginx/conf.d:/etc/nginx/conf.d            # Пользовательские конфигурации
      - ./nginx/errand:/etc/nginx/errand            # Пользовательские страницы ошибок
      - ./nginx/ssl:/etc/nginx/ssl                  # Фиктивный SSL для базовых настроек
      - ./nginx/auth:/etc/nginx/auth                # Файлы базовой аутенфикации
      - ./nginx/log:/var/log/nginx                  # Логи NGINX
      - ./certbot/conf:/etc/letsencrypt             # Сертификаты Let’s Encrypt
      - ./certbot/www:/var/www/certbot              # Файлы проверки Let’s Encrypt

  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./certbot/log:/var/log/letsencrypt          # Логи CertBot Let’s Encrypt
      - ./certbot/conf:/etc/letsencrypt             # Сертификаты Let’s Encrypt
      - ./certbot/www:/var/www/certbot              # Файлы проверки Let’s Encrypt

networks:
  default:
    name: app
